# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Bienvenida.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Bienvenida(object):
    def setupUi(self, Bienvenida):
        Bienvenida.setObjectName("Bienvenida")
        Bienvenida.resize(789, 568)
        self.label = QtWidgets.QLabel(Bienvenida)
        self.label.setGeometry(QtCore.QRect(110, 70, 631, 301))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Bienvenida)
        self.pushButton.setGeometry(QtCore.QRect(580, 450, 191, 101))
        self.pushButton.setStyleSheet("background-color: rgb(39, 143, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Arial Rounded MT Bold\";\n"
"border-radius: 10px;")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Bienvenida)
        QtCore.QMetaObject.connectSlotsByName(Bienvenida)

    def retranslateUi(self, Bienvenida):
        _translate = QtCore.QCoreApplication.translate
        Bienvenida.setWindowTitle(_translate("Bienvenida", "Form"))
        self.label.setText(_translate("Bienvenida", "¡BIENVENIDO AL CURSO BÁSICO DE GIT!"))
        self.pushButton.setText(_translate("Bienvenida", "PRESIONA PARA COMENZAR"))
