# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Lección_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Leccion1(object):
    def setupUi(self, Leccion1):
        Leccion1.setObjectName("Leccion1")
        Leccion1.resize(703, 544)
        self.label = QtWidgets.QLabel(Leccion1)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(20, 80, 651, 271))
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Leccion1)
        self.pushButton.setGeometry(QtCore.QRect(510, 430, 171, 81))
        self.pushButton.setStyleSheet("background-color: rgb(39, 143, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Arial Rounded MT Bold\";\n"
"border-radius: 10px;")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Leccion1)
        QtCore.QMetaObject.connectSlotsByName(Leccion1)

    def retranslateUi(self, Leccion1):
        _translate = QtCore.QCoreApplication.translate
        Leccion1.setWindowTitle(_translate("Leccion1", "Form"))
        self.label.setText(_translate("Leccion1", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600;\">¿QUÉ ES GIT?</span></p><p align=\"center\"><span style=\" font-size:20pt;\">Git es un sistema de control de versiones que te permite guardar cambios, regresar a versiones anteriores y trabajar en equipo sin perder código.</span></p></body></html>"))
        self.pushButton.setText(_translate("Leccion1", "Siguiente"))
