# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Lección_3.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(749, 540)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(170, 10, 411, 91))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 651, 411))
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(550, 410, 181, 111))
        self.pushButton.setStyleSheet("background-color: rgb(39, 143, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Arial Rounded MT Bold\";\n"
"border-radius: 10px;")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">AGREGAR ARCHIVOS AL ÁREA DE PREPARACIÓN (STAGING)</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"justify\"><span style=\" font-size:12pt; font-weight:600;\">GIT ADD</span></p><p align=\"justify\"><span style=\" font-size:12pt;\">¿Para qué sirve este comando?</span></p><p align=\"justify\"><span style=\" font-size:12pt;\">Agrega archivos al área de preparación (staging), donde Git guarda los cambios que serán incluidos en el próximo commit.</span></p><p align=\"justify\"><br/><span style=\" font-size:12pt;\">¿Cómo se usa?</span></p><p align=\"justify\"><span style=\" font-size:12pt;\">Agregar un archivo específico:</span></p><p align=\"justify\"><span style=\" font-size:12pt;\">git add archivo.py</span></p><p align=\"justify\"><span style=\" font-size:12pt;\">Agregar todos los archivos modificados:</span></p><p align=\"justify\"><span style=\" font-size:12pt;\">git add.</span></p><p align=\"justify\"><br/></p><p align=\"justify\"><span style=\" font-size:12pt;\">¿Qué ocurre al ejecutarlo?</span></p><p align=\"justify\"><span style=\" font-size:12pt;\">1. Los cambios pasan al staging.<br/>2. Git deja los archivos listos para el commit.<br/>3. Permite controlar exactamente qué cambios deseas guardar.</span></p></body></html>"))
        self.pushButton.setText(_translate("Form", "Siguiente"))
