# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Lección_4.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(793, 566)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(240, 20, 321, 41))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(100, 60, 591, 361))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(560, 450, 211, 81))
        self.pushButton.setStyleSheet("background-color: rgb(39, 143, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Arial Rounded MT Bold\";\n"
"border-radius: 10px;")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">CREAR UN COMMIT</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">GIT COMMIT </span></p><p><span style=\" font-size:12pt;\">¿Para qué sirve este comando? </span></p><p><span style=\" font-size:12pt;\">Guarda los cambios del área de preparación (staging) en el historial del repositorio, junto con un mensaje descriptivo. </span></p><p><span style=\" font-size:12pt;\">¿Cómo se usa? </span></p><p><span style=\" font-size:12pt;\">Realizar un commit con un mensaje: </span></p><p><span style=\" font-size:12pt;\">git commit -m &quot;Mensaje describiendo cambios&quot; </span></p><p><span style=\" font-size:12pt;\">¿Qué ocurre al ejecutarlo? </span></p><p align=\"justify\"><span style=\" font-size:12pt;\">1. Los cambios quedan registrados permanentemente en el historial<br/>2. Cada commit incluye un mensaje que explica qué se hizo<br/>3. Permite llevar un control claro y ordenado de la evolución del proyecto </span></p></body></html>"))
        self.pushButton.setText(_translate("Form", "SIGUIENTE"))
