# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Lección_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Leccion2(object):
    def setupUi(self, Leccion2):
        Leccion2.setObjectName("Leccion2")
        Leccion2.resize(748, 559)
        self.label = QtWidgets.QLabel(Leccion2)
        self.label.setGeometry(QtCore.QRect(170, 40, 391, 71))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Leccion2)
        self.label_2.setGeometry(QtCore.QRect(120, 110, 481, 131))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Leccion2)
        self.label_3.setGeometry(QtCore.QRect(160, 230, 391, 151))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(Leccion2)
        self.pushButton.setGeometry(QtCore.QRect(530, 470, 201, 71))
        self.pushButton.setStyleSheet("background-color: rgb(39, 143, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Arial Rounded MT Bold\";\n"
"border-radius: 10px;")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Leccion2)
        QtCore.QMetaObject.connectSlotsByName(Leccion2)

    def retranslateUi(self, Leccion2):
        _translate = QtCore.QCoreApplication.translate
        Leccion2.setWindowTitle(_translate("Leccion2", "Form"))
        self.label.setText(_translate("Leccion2", "<html><head/><body><p align=\"justify\"><span style=\" font-size:18pt; font-weight:600;\">INICIALIZA UN REPOSITORIO</span></p></body></html>"))
        self.label_2.setText(_translate("Leccion2", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">GIT INIT</span></p><p align=\"center\"><span style=\" font-size:12pt;\">¿Qué hace este comando?</span></p><p align=\"center\"><span style=\" font-size:12pt;\">Inicializa un nuevo repositorio de Git en la carpeta actual.</span></p></body></html>"))
        self.label_3.setText(_translate("Leccion2", "<html><head/><body><p align=\"justify\"><span style=\" font-size:12pt;\">¿Qué ocurre al ejecutarlo?</span></p><p align=\"justify\"><span style=\" font-size:12pt;\">1.  Se crea la carpeta .git</span></p><p align=\"justify\"><span style=\" font-size:12pt;\">2. Git comienza a registrar el historial de cambios</span></p><p align=\"justify\"><span style=\" font-size:12pt;\">3. Tu carpeta se convierte en un repositorio</span></p></body></html>"))
        self.pushButton.setText(_translate("Leccion2", "Siguiente"))
