# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Pantalla_De_Inicio.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Pantalla_De_Inicio(object):
    def setupUi(self, Pantalla_De_Inicio):
        Pantalla_De_Inicio.setObjectName("Pantalla_De_Inicio")
        Pantalla_De_Inicio.resize(774, 575)
        font = QtGui.QFont()
        font.setPointSize(22)
        Pantalla_De_Inicio.setFont(font)
        Pantalla_De_Inicio.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(Pantalla_De_Inicio)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(270, 130, 231, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(136, 204, 25);\n"
"color: rgb(255, 255, 255);\n"
"font: 9pt \"Arial Rounded MT Bold\";\n"
"border-radius: 10px;\n"
"\n"
"")
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(270, 310, 231, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(136, 204, 25);\n"
"color: rgb(255, 255, 255);\n"
"font: 9pt \"Arial Rounded MT Bold\";\n"
"border-radius: 10px;\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(470, 590, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(610, 410, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color: rgb(39, 143, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 9pt \"Arial Rounded MT Bold\";\n"
"border-radius: 10px;\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(270, 220, 231, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(136, 204, 25);\n"
"color: rgb(255, 255, 255);\n"
"font: 9pt \"Arial Rounded MT Bold\";\n"
"border-radius: 10px;\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 50, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName("label")
        Pantalla_De_Inicio.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Pantalla_De_Inicio)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 774, 46))
        self.menubar.setObjectName("menubar")
        Pantalla_De_Inicio.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Pantalla_De_Inicio)
        self.statusbar.setObjectName("statusbar")
        Pantalla_De_Inicio.setStatusBar(self.statusbar)

        self.retranslateUi(Pantalla_De_Inicio)
        QtCore.QMetaObject.connectSlotsByName(Pantalla_De_Inicio)

    def retranslateUi(self, Pantalla_De_Inicio):
        _translate = QtCore.QCoreApplication.translate
        Pantalla_De_Inicio.setWindowTitle(_translate("Pantalla_De_Inicio", "MainWindow"))
        self.pushButton.setText(_translate("Pantalla_De_Inicio", "INICIAR CURSO"))
        self.pushButton_3.setText(_translate("Pantalla_De_Inicio", "SALIR"))
        self.pushButton_4.setText(_translate("Pantalla_De_Inicio", "PushButton"))
        self.pushButton_5.setText(_translate("Pantalla_De_Inicio", "ENTER"))
        self.pushButton_2.setText(_translate("Pantalla_De_Inicio", "¿QUÉ APRENDERÁS?"))
        self.label.setText(_translate("Pantalla_De_Inicio", "APRENDIENDO GITHUB"))
