# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Lección_5.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 50, 601, 101))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(170, 150, 471, 311))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(570, 480, 171, 41))
        self.pushButton.setStyleSheet("background-color: rgb(39, 143, 255);\n"
"\n"
"\n"
"color: rgb(255, 255, 255);\n"
"\n"
"\n"
"font: 10pt \"Arial Rounded MT Bold\";\n"
"\n"
"\n"
"border-radius: 10px;")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "CONECTAR CON UN REPOSITORIO REMOTO"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt; font-weight:600;\">GIT REMOTE ADD ORIGIN</span></p><p align=\"center\"><span style=\" font-size:9pt;\">¿Qué hace este comando? </span></p><p align=\"center\"><span style=\" font-size:9pt;\">Conceta tu proyecto local con un repositorio en GitHub</span></p><p><span style=\" font-size:9pt;\"><br/></span></p><p><span style=\" font-size:9pt;\">¿Que ocurre al ejecutarlo?</span></p><p><span style=\" font-size:9pt;\">1. Git sabe a que repositorio remoto debe enviar los cambios.</span></p><p><span style=\" font-size:9pt;\">2. Se establece el nombre origin como referencia por defecto.</span></p><p><span style=\" font-size:9pt;\">3. Permite inicair sincronización con GitHub mediante push y pull.</span></p><p><span style=\" font-size:9pt;\"><br/></span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Siguiente"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
