# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Sección_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(590, 470, 171, 41))
        self.pushButton_2.setStyleSheet("background-color: rgb(39, 143, 255);\n"
"\n"
"\n"
"color: rgb(255, 255, 255);\n"
"\n"
"\n"
"font: 10pt \"Arial Rounded MT Bold\";\n"
"\n"
"\n"
"border-radius: 10px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(170, 20, 571, 491))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "Siguiente"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">¿Qué aprenderas en GitHub?</p><p align=\"center\"><br/></p><p><a name=\"docs-internal-guid-22b34331-7fff-bd37-c1e4-e7a9e2924f35\"/><span style=\" font-family:\'Arial,sans-serif\'; font-size:9pt; font-weight:400; color:#000000; background-color:transparent;\">-</span><span style=\" font-family:\'Arial,sans-serif\'; font-size:9pt; font-weight:400; color:#000000; background-color:transparent;\"> Qué es Git</span></p><p><span style=\" font-family:\'Arial,sans-serif\'; font-size:9pt; font-weight:400; color:#000000; background-color:transparent;\">- Crear un repositorio (git init)</span></p><p><span style=\" font-family:\'Arial,sans-serif\'; font-size:9pt; font-weight:400; color:#000000; background-color:transparent;\">- Agregar cambios (git add)</span></p><p><span style=\" font-family:\'Arial,sans-serif\'; font-size:9pt; font-weight:400; color:#000000; background-color:transparent;\">- Guardar versiones (git commit)</span></p><p><span style=\" font-family:\'Arial,sans-serif\'; font-size:9pt; font-weight:400; color:#000000; background-color:transparent;\">- Conectar con GitHub (git remote)</span></p><p><span style=\" font-family:\'Arial,sans-serif\'; font-size:9pt; font-weight:400; color:#000000; background-color:transparent;\">- Subir código (git push)</span></p><p><span style=\" font-size:9pt;\"><br/></span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
