# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Lección_6.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 60, 511, 401))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 40, 301, 121))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(570, 470, 171, 41))
        self.pushButton.setStyleSheet("background-color: rgb(39, 143, 255);\n"
"\n"
"\n"
"color: rgb(255, 255, 255);\n"
"\n"
"\n"
"font: 10pt \"Arial Rounded MT Bold\";\n"
"\n"
"\n"
"border-radius: 10px;")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p><p align=\"center\"><span style=\" font-size:9pt;\">GIT PUSH<br/></span><span style=\" font-size:9pt; font-weight:400;\">¿Qué hace este comando?</span></p><p align=\"center\"><span style=\" font-size:9pt; font-weight:400;\">Sube el código desde tu repositorio local hacia el repositorio remoto.</span></p><p><br/></p><p><span style=\" font-size:9pt; font-weight:400;\">¿Qué ocurre al ejecutarlo?</span></p><p><span style=\" font-size:9pt; font-weight:400;\">1. Se suben tus commits a la rama main en GitHub.</span></p><p><span style=\" font-size:9pt; font-weight:400;\">2. El parámetro -u establece la rama remota como predeterminada.</span></p><p><span style=\" font-size:9pt; font-weight:400;\">3. A partir de ahora, podrás usar simplemente git push.</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "SUBIR EL CÓDIGO"))
        self.pushButton.setText(_translate("MainWindow", "Siguiente"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
